import React from "react";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import ImageTextBlock, { COLORS } from "../components/ImageTextBlock";
import MainLayout from "../layout/main";
import { ACTIONS } from "../components/Action";
import Banner from "../components/Banner";
import TextBlock from "../components/TextBlock";

export default class HostPage extends React.Component {
	static async getInitialProps() {
		return {
			banner: {
				message: "BUILD LASTING FRIENDSHIPS",
				image: "/static/images/host-student-banner.jpg"
			},
			sections: [[
				{
					title: "A TYPICAL YEAR",
					headerAlign: "center",
					textAlign: "justify",
					content: `
At the beginning of the fall and spring semesters, we host a welcome lunch to tell new international students about our program and invite them to sign up. We then invite community hosts to select students using an online host-student matching database.

Students are invited to get together once a month or more with their hosts. Activities can range from special events (holiday celebrations, sightseeing trips, hiking outings, etc.) to everyday activities like shopping and dining out. Students sometimes visit hosts' homes to prepare foods native to their homeland.

While the program officially ends after the first academic year, lifelong friendships and connections are often formed with students and their families back home. Many of us have found our lives immeasurably enriched by our friendships with young people from around the world.`
				},
			], [{
				title: "SEE YOUR WORLD WITH FRESH EYES",
				image: "./static/images/halloween.jpg",
				content: `
International students describe International Friends as an invaluable asset for learning about American life outside of the academic environment. Tucson citizens who have hosted students have discovered the world at their doorstep! They "will never watch the evening news in the same way again."

Our students are the future leaders in their fields in their respective countries. The goodwill generated by this relationship will affect both students and hosts for the rest of their lives.`,
				action: [{
					type: ACTIONS.SIGNUP,
					label: "Apply to Host"
				}]
			}, {
				title: "HOW HOSTING WORKS",
				image: "/static/images/cooking2.jpg",
				content: `
Students are assigned to hosts for a period of one year, as long as it is mutually satisfying. Although the relationships may continue well beyond the year, we hope hosts will make themselves available to other first year students in upcoming years.

Any student queries regarding the following should be referred to the office of International Student Services:

* Employment instructions
* Immigration and visa issues
* Academic problems with professors, advisors and administrators
* Financial problems
* Major medical problems`,
				actions: [{
					type: ACTIONS.READMORE,
					href: "/guidelines"
				}]
			}]]
		};
	}

	render() {
		const { banner, sections } = this.props;
		return (
			<MainLayout>
				<Banner {...banner} />
				<Container>
					<Row>
						<Col md={12}>
							<TextBlock {...sections[0][0]} />
						</Col>
					</Row>
					<ImageTextBlock {...sections[1][0]} color={COLORS.LIGHT} invert />
					<ImageTextBlock {...sections[1][1]} />
				</Container>
			</MainLayout>
		);
	}
}
