import { Component } from "react";
import ReactMarkDown from "react-markdown";
import { Container } from "react-bootstrap";
import MainLayout from "../layout/main";

export default class ByLaws extends Component {
	static async getInitialProps() {
		return {
			letter: {
				header:
					`
## Letter from the chair
`,
				content:
					`Dear International Friends, Students, and Guests,

Thank you for your interest in International Friends, Inc., Tucson, Arizona. International Friends has been in existence since 1952 - one of the oldest organizations of this type in the United States.

International Friends, Inc. works directly with the office of International Student Programs and Services at the University of Arizona and is governed by a Board of Directors composed of student and citizen representatives. I hope you will consider playing an active role in our organization - as student participant or local host, committee member or volunteer at one of our annual events. You will find descriptions of our activities on our website.

International students describe International Friends as an invaluable asset for learning about American life outside of the academic environment. Tucson citizens who have hosted students have discovered the world at their doorstep! As a new host told me last year, "We will never watch the evening news in the same way again."

Is this program worth it? I would say, unequivocally, YES. Our students are the future leaders in their fields in their respective countries. The goodwill generated by this relationship will affect both student and host for the rest of their lives.

International Friends, Inc. is for everyone and anyone who wants to make a difference in the world. If you have a friend, neighbor, family member, colleague or fellow international student who may be interested, please pass this information on to them.

I hope you will take the time to visit our informative website. For further information about Tucson International Friends, please feel free to contact us online at [info@ifriendstucson.org]. Questions regarding the University of Arizona policies and practices, enrollment, etc. should be directed to: [isps@email.arizona.edu].

Join us! A new friend is waiting...

Sincerely,

Randy Spalding and Pat Gilman, Co-chairs International Friends, Inc.
`
			}
		};
	}

	render() {
		const { letter: { header, content } } = this.props;
		return (
			<MainLayout>
				<Container style={{
					paddingTop: "10em",
					paddingBottom: "10em"
				}}>
					<ReactMarkDown source={header} className="text-center" />
					<ReactMarkDown source={content} />
				</Container>
			</MainLayout>
		);
	}
}
